const {
	convertToTwoDigitTime,
} = require("../../functions/intro/convert-to-two-digit-time")

test("Testing formatTime Function: Hours", () => {
	expect(convertToTwoDigitTime(0, "hours")).toBe("12")
	expect(convertToTwoDigitTime(1, "hours")).toBe("01")
	expect(convertToTwoDigitTime(2, "hours")).toBe("02")
	expect(convertToTwoDigitTime(3, "hours")).toBe("03")
	expect(convertToTwoDigitTime(4, "hours")).toBe("04")
	expect(convertToTwoDigitTime(5, "hours")).toBe("05")
	expect(convertToTwoDigitTime(6, "hours")).toBe("06")
	expect(convertToTwoDigitTime(7, "hours")).toBe("07")
	expect(convertToTwoDigitTime(8, "hours")).toBe("08")
	expect(convertToTwoDigitTime(9, "hours")).toBe("09")
	expect(convertToTwoDigitTime(10, "hours")).toBe("10")
	expect(convertToTwoDigitTime(11, "hours")).toBe("11")
	expect(convertToTwoDigitTime(12, "hours")).toBe("12")
	expect(convertToTwoDigitTime(13, "hours")).toBe("01")
	expect(convertToTwoDigitTime(14, "hours")).toBe("02")
	expect(convertToTwoDigitTime(15, "hours")).toBe("03")
	expect(convertToTwoDigitTime(16, "hours")).toBe("04")
	expect(convertToTwoDigitTime(17, "hours")).toBe("05")
	expect(convertToTwoDigitTime(18, "hours")).toBe("06")
	expect(convertToTwoDigitTime(19, "hours")).toBe("07")
	expect(convertToTwoDigitTime(20, "hours")).toBe("08")
	expect(convertToTwoDigitTime(21, "hours")).toBe("09")
	expect(convertToTwoDigitTime(22, "hours")).toBe("10")
	expect(convertToTwoDigitTime(23, "hours")).toBe("11")
})

test("Testing formatTime Function: Minutes", () => {
	expect(convertToTwoDigitTime(59)).toBe("59")
	expect(convertToTwoDigitTime(13)).toBe("13")
	expect(convertToTwoDigitTime(49)).toBe("49")
	expect(convertToTwoDigitTime(9)).toBe("09")
	expect(convertToTwoDigitTime(1)).toBe("01")
	expect(convertToTwoDigitTime(0)).toBe("00")
	expect(convertToTwoDigitTime(2)).toBe("02")
	expect(convertToTwoDigitTime(3)).toBe("03")
	expect(convertToTwoDigitTime(4)).toBe("04")
	expect(convertToTwoDigitTime(5)).toBe("05")
})
